---
- name: Copy application WAR file to host
  copy:
    src: "{{ java_app }}"
    dest: /tmp
  tags:
    - deploy

- name: Deploy Ticket Monster to JBoss
  jboss:
    deploy_path: /usr/share/jboss-as/standalone/deployments/
    src: /tmp/{{ java_app }}
    deployment: "{{ java_app }}"
    state: present
  tags:
    - deploy
